### ISSUE TITLE
Apparmor compatibility problem

### ISSUE THREAD

**Issue by fnzv** [entercloudsuite/ansible-strongswan#1]
Running the role on Ubuntu 14.04 LTS works fine but the IPSec session won't go UP on both endpoints because of Apparmor.

Error:
Mar  6 11:41:34 ubuntu14 charon: 00[CFG] expanding file expression '/etc/ipsec.secrets.d/*' failed
Mar  6 11:41:34 ubuntu14 kernel: [4324136.167735] type=1400 audit(1520336494.035:24): apparmor="DENIED" operation="open" profile="/usr/lib/ipsec/charon" name="/etc/ipsec.secrets.d/" pid=13253 comm="charon" re
quested_mask="r" denied_mask="r" fsuid=0 ouid=0

Temp Fix:
apt-get install -y apparmor-utils
aa-complain /usr/lib/ipsec/charon
aa-complain /usr/lib/ipsec/stroke

**Comment by jsecchiero** [comment]
Hi Fnzv!,
thanks for the issue, unfortunately can't replicate with Ubuntu 14.04.2 LTS.
In fact all needed roles are added in /etc/apparmor.d/usr.lib.ipsec.charon.
Have you tried with a clean installation?
Thanks
Jacopo
